///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String avatar1 = 'assets/Images/avatar1.svg';
  static const String avatar2 = 'assets/Images/avatar2.svg';
  static const String dashboard = 'assets/Images/dashboard.svg';
  static const String expense = 'assets/Images/expense.svg';
  static const String income = 'assets/Images/income.svg';
  static const String logout = 'assets/Images/logout.svg';
  static const String maskGroup = 'assets/Images/mask_group.svg';
  static const String money = 'assets/Images/money.svg';
  static const String moneys = 'assets/Images/moneys.svg';
  static const String montserratRegular = 'assets/Fonts/Montserrat-Regular.ttf';
  static const String myInvest = 'assets/Images/my_invest.svg';
  static const String myTransactions = 'assets/Images/my_transactions.svg';
  static const String setting2 = 'assets/Images/setting-2.svg';
  static const String stat = 'assets/Images/stat.svg';
  static const String wallet2 = 'assets/Images/wallet-2.svg';

}
